### ISSUE TITLE
OCLC FAST Concepts search results have id.loc.gov URIs

### ISSUE THREAD

**Issue by elrayle** [cul-it/qa_server#14]
@sfolsom @jak473 Metadata team:  What do you want to do about the fact that OCLC FAST searching for Concepts returns results with the subject URIs that are id.loc.gov URIs instead of OCLC FAST URIs?

**Comment by sfolsom** [comment]
Search for the schema:Intangible, Event, Persons, etc. (the primary entities in FAST) and use the Concepts (external aligned entities) as context nodes.

**Comment by sfolsom** [comment]
We're moving away from caching, so this issue can be closed.
