### ISSUE TITLE
Tweak LoC Genre indexing

### ISSUE THREAD

**Issue by elrayle** [cul-it/qa_server#20]
Work with metadata team and Dave to identify fields for searching and weighting of search results.

See @sfolsom's document describing what context should be searched and what should be displayed to the user...  [Indexing of External Data for Look-ups](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=696491968)

General notes about indexing:

* prefLabel (or other primary label field) should be stem indexed and non-stem indexed.
* an exact match on the non-stem indexed prefLabel field should have the highest weighting in the index
* matches on the stemmed prefLabel field should have the second highest weighting in the index
* other fields (e.g. variant labels, notes, etc.) should have a lower weighting

As we explore effects of indexing, the last area of other fields may be tweaked to determine the best weighting.

**Comment by zimeon** [comment]
Discussion in meeting:
  * Try first pass applying general rules for lookup that weight prefLabel
  * For future work we should get some test data for a particular authority (LCGFT) -- but likely 2-3 weeks before we could use
  * Ideas for test data:
    * perhaps start with of order 20 cases
    * cases where terms are short/long
    * cases where special characters (e.g. comma, apostrophe) are included
    * cases where we expect a particular term to be top hit (e.g. "Soul Music"), and cases where we expect particular terms to come "high" (e.g. "Soul Music" in top 10 for search on "Soul")

**Comment by sfolsom** [comment]
We're moving away from caching, so this issue can be closed.
