### ISSUE TITLE
Add status validation scenarios for Getty AAT hierarchies

### ISSUE THREAD

**Issue by elrayle** [cul-it/qa_server#30]
One search query is needed for each of the following hierarchy levels...

| Hierarchy Level | Query |
| --- | --- |
| "Activities" |  |
| "Activities__Disciplines" | |
| "Activities__Events" | |
| "Activities__Functions" | |
| "Activities__Physical_and_Mental" | |
| "Activities__Processes_and_Techniques" | |
| "Activities__activities" | |
| "Agents" | domestic |
| "Agents__Living_Organisms" | domestic |
| "Agents__Organizations" | |
| "Agents__People" | domestic |
| "Agents__agents" | |
| "Associated_Concepts" | |
| "Associated_Concepts__Associated_Concepts" | |
| "Brand_Names" | |
| "Brand_Names__Brand_Names" | |
| "Materials" | |
| "Materials__Materials" | |
| "Objects" | |
| "Objects__Built_Environment" | |
| "Objects__Components" | |
| "Objects__Furnishings_and_Equipment" | |
| "Objects__Object_Genres" | |
| "Objects__Object_Groupings and Systems" | |
| "Objects__Visual_and_Verbal_Communication" | |
| "Physical_Attributes" | |
| "Physical_Attributes__Attributes_and_Properties" | |
| "Physical_Attributes__Color" | |
| "Physical_Attributes__Conditions_and_Effects" | |
| "Physical_Attributes__Design_Elements" | |
| "Styles_and_Periods" | |
| "Styles_and_Periods__Styles_and_Periods" | |

@sfolsom Can you help fill these in?

**Comment by sfolsom** [comment]
Hierarchy Level | Query
-- | --
"Activities" |  Events
"Activities__Disciplines" |  film
"Activities__Events" |  exhibitions
"Activities__Functions" |  inspection
"Activities__Physical_and_Mental" |  public speaking
"Activities__Processes_and_Techniques" |  transporting
"Activities__activities" |  
"Agents" | domestic
"Agents__Living_Organisms" | domestic
"Agents__Organizations" |  funding agencies
"Agents__People" | domestic
"Agents__agents" |  
"Associated_Concepts" |  social science
"Associated_Concepts__Associated_Concepts" |  air quality
"Brand_Names" |  brand name additives
"Brand_Names__Brand_Names" |  tyvek
"Materials" |  
"Materials__Materials" |  copper
"Objects" |  built environment
"Objects__Built_Environment" | backstops
"Objects__Components" |   reveals
"Objects__Furnishings_and_Equipment" |  Boston rocker
"Objects__Object_Genres" |  sun compasses
"Objects__Object_Groupings and Systems" |  libraries
"Objects__Visual_and_Verbal_Communication" |  admission ticket
"Physical_Attributes" |  
"Physical_Attributes__Attributes_and_Properties" |   density
"Physical_Attributes__Color" |  pearl
"Physical_Attributes__Conditions_and_Effects" |  cracks
"Physical_Attributes__Design_Elements" |  compass roses
"Styles_and_Periods" |  
"Styles_and_Periods__Styles_and_Periods" |  Contemporary

**Comment by sfolsom** [comment]
Made a first pass. Still need to think about whether/when hierarchy positions need to be search terms or whether they strictly aid in browse/filter navigation.

**Comment by elrayle** [comment]
@sfolsom I updated your table with test results.  3 failed.  For the first two, you did not indicate a value.  I tried one of the values from a related hierarchy-subhierarchy.  So perhaps those combos should not be supported?

The third failure for "Objects__Object_Genres" searching for "sun compasses" was specified by you, but it fails to return any results.  If you are sure this is a good search query, then I will dig around on our side to see why it doesn't return any results.

**Comment by sfolsom** [comment]
Can you define "fail"? Is the goal that the test strings be an exact match of a particular entity? I can adjust the terms based on the response. Events (activities) is an entity in AAT <http://vocab.getty.edu/aat/300069084>, and there are other types of events that a "events" search should get hits for. I'm glad "sun compasses" failed for that facet; it's in a different part of the hierarchy. :) . I'll replace it with a better example. The Agents term wasn't one I supplied, but I can add one.

**Comment by sfolsom** [comment]
Updated "Agents__agents" and "Objects__Object_Genres".

**Comment by elrayle** [comment]
I continue to have problems with Activities__activities and Agents__agents.  Both of these are marked as general context instead of hierarchy facet at getty aat.  In conversations in slack, it was determined that those two parts of the getty aat hierarchy should not be surfaced to end users for search.

@sfolsom Do you concur?

**Comment by sfolsom** [comment]
Agreed. Tagging something classed as an Agent or Activity with these general skos:Concepts doesn’t add any new semantics to the data.

**Comment by elrayle** [comment]
Fixed by PR #32.  In production... closing.
