### ISSUE TITLE
Brand the service as the "LD4L Authority Lookup Service"

### ISSUE THREAD

**Issue by zimeon** [cul-it/qa_server#5]
I discussed with Dean and we think it should stay at lookup.ld4l.org and be branded "LD4L Authority Lookup Service"

Underneath the title we should explain:

> This service provide authority lookup for single terms and search for terms matching a query. It has been created as part of the [LD4L Labs](https://www.ld4l.org/ld4l-labs) project, and is operated by [Cornell University Library](https://www.library.cornell.edu) in collaboration with the [School of Library and Information Science, University of Iowa](https://www.slis.uiowa.edu/). This work was funded through a grant from the Andrew W. Mellon Foundation.

I'm guessing at how Dave would want the Iowa contribution acknowledged so you might ping him to see whether that is OK.

**Comment by eichmann** [comment]
That text looks fine to me.
