### ISSUE TITLE
Geonames - create subauth that prioritizes country, state, and region

### ISSUE THREAD

**Issue by elrayle** [cul-it/qa_server#6]
Request by @hudajkhan 

## Description

Searching Geonames for something like 'Ithaca' returns results that include hotels and other establishments in and around Ithaca, but not the city of Ithaca itself.  Is it possible to use subauthorities to make a query that only returns results that are country, state, or region?

## Expected Results

http://lookup.ld4l.org/qa/search/linked_data/geonames_ld4l_cache?q=Ithaca&maxRecords=4

```
[
    {
        "uri":"http://sws.geonames.org/261707/",
        "id":"http://sws.geonames.org/261707/",
        "label":"Ithaca (GR)"
    },
    {
        "uri":"http://sws.geonames.org/5122432/",
        "id":"http://sws.geonames.org/5122432/",
        "label":"Ithaca (US)"
    },
    {
        "uri":"http://sws.geonames.org/8133849/",
        "id":"http://sws.geonames.org/8133849/",
        "label":"Ithaca (GR)"
    },
    {
        "uri":"http://sws.geonames.org/261708/",
        "id":"http://sws.geonames.org/261708/",
        "label":"Itháki (GR)"
    }
]
```

## Actual Results

http://lookup.ld4l.org/qa/search/linked_data/geonames_ld4l_cache?q=Ithaca&maxRecords=4

![image](https://user-images.githubusercontent.com/6855473/37067187-bc66cd10-2176-11e8-8928-18f89e2ccc8a.png)

**Comment by elrayle** [comment]
The triple in the results that indicates the entity's type of place is `gn:featureCode`.

Examples,

**Comfort Inn Ithaca (US)**
```
<gn:featureClass rdf:resource="http://www.geonames.org/ontology#S"/>
    where S - spot, building, farm
<gn:featureCode rdf:resource="http://www.geonames.org/ontology#S.HTL"/>
    where, S.HTL indicates (S) spot, building, farm - (HTL) hotel
```

**Ithaca (US)**
```
<gn:featureClass rdf:resource="http://www.geonames.org/ontology#P"/>
    where P - city, village
<gn:featureCode rdf:resource="http://www.geonames.org/ontology#P.PPLA2"/>
    where P.PPLA2 indicates (P) city, village - (PPLA2) seat of a second-order administrative division
```

The full list is at http://www.geonames.org/export/codes.html

They can be acquired from the ontology as rdfxml using... 
```
curl -L -D - -H 'Accept: application/n-triples' 'http://www.geonames.org/ontology/ontology_v3.1.rdf'
```

QA does not have any code for interpreting ontology rdfxml.

**Comment by elrayle** [comment]
From Dave:

> Re the geonames data - they don't break things out by ontology classes (everything's an instance of feature); instead they have a hierarchy of feature codes (see http://www.geonames.org/export/codes.html) with nine major categories.  Would indexing by major category suffice?  There are dozens of individual categories (e.g., a standing body of water in a cave).

**Comment by elrayle** [comment]
From @hudajkhan 
> if the major category is country, state, region, that sounds fine.  We can revisit if the catalogers need anything more granular but that should suffice for now.  Thanks!

**Comment by elrayle** [comment]
To summarize, the proposal is for Dave to index on major category.  And QA will surface these as subauthorities.

| featureClass | label | entity | subauth |
| -------------- | ------ | ------ | --------- | 
| A | country, state, region | | |
| P | city, village | | |
| H | stream, lake | | |
| L | parks, area | | |
| R | road, railroad | | |
| S | spot, building, farm | | |
| T | mountain, hill, rock | | |
| U | undersea | | |
| V | forest, heath | | |

Entity and subauth names TBD.

**Comment by elrayle** [comment]
Context from C. Eslao...
> when we've run python scripts to do quick & dirty geonames recon on harvard data, we've used properties like gn:fcodeName to prefer entities that are coded as "independent political entity" or "historical political entity" (for countries) and "first-order administrative division" (for states, provinces, etc)
> otherwise the top result seems arbitrary and not necessarily the kind of entity that legacy data tends to record

**Comment by elrayle** [comment]
From @eichmann...
>My Lucene indexer currently uses a most specific label (US Eng, Eng, any lang COALESCE) for a search hit label, and indexes on that plus alternate names, official names, parent country, parent feature and parentADM1-4 label.  Given the current conversation, it looks like I should drop anything about parents from the indexed text.

**Comment by eichmann** [comment]
All feature classes are now separately queryable, plus a combined A & P.  See the authority slack channel for further discussion of the new index argument and how it can alter the nature of results.
